spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment_db?reWriteBatchedStatements=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000


server:
  port: 8080

redisson:
  config: |
    singleServerConfig:
      address: "redis://127.0.0.1:6379"
      connectionMinimumIdleSize: 5
      connectionPoolSize: 10

logging:
  level:
    com.delta.ingestion: DEBUG